.TH argparse-manpage "1" Manual
.SH NAME
argparse-manpage
.SH SYNOPSIS
.B argparse-manpage
[-h] {update,purge,linux,windows} ...
.SH DESCRIPTION
Offline command line lookup utility for GTFOBins (https://gtfobins.github.io/)
.br
and LOLBAS (https://lolbas\-project.github.io/)
.SH OPTIONS
.SS
\fBSub-commands\fR
.TP
\fBargparse-manpage\fR \fI\,update\/\fR
update local copies of repositories
.TP
\fBargparse-manpage\fR \fI\,purge\/\fR
remove local copies of repositories
.TP
\fBargparse-manpage\fR \fI\,linux\/\fR
search the local copy of GTFOBins
.TP
\fBargparse-manpage\fR \fI\,windows\/\fR
search the local copy of LOLBAS
.SH OPTIONS 'argparse-manpage update'
usage: argparse-manpage update [-h] [-r repo]


.TP
\fB\-r\fR repo, \fB\-\-repo\fR repo
Only update the specified repository

.SH OPTIONS 'argparse-manpage purge'
usage: argparse-manpage purge [-h] [-r repo]


.TP
\fB\-r\fR repo, \fB\-\-repo\fR repo
Only delete the specified repository

.SH OPTIONS 'argparse-manpage linux'
usage: argparse-manpage linux [-h] [-l list]
                              {shell,cmd,rev,nrev,bind,nbind,upload,download,write,read,load,suid,sudo,cap,lsuid,all}
                              ...

.SS
\fBSub-commands\fR
.TP
\fBargparse-manpage linux\fR \fI\,shell\/\fR
search the 'shell' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,cmd\/\fR
search the 'command' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,rev\/\fR
search the 'reverse-shell' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,nrev\/\fR
search the 'non-interactive-reverse-shell' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,bind\/\fR
search the 'bind-shell' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,nbind\/\fR
search the 'non-interactive-bind-shell' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,upload\/\fR
search the 'file-upload' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,download\/\fR
search the 'file-download' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,write\/\fR
search the 'file-write' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,read\/\fR
search the 'file-read' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,load\/\fR
search the 'library-load' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,suid\/\fR
search the 'suid' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,sudo\/\fR
search the 'sudo' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,cap\/\fR
search the 'capabilities' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,lsuid\/\fR
search the 'limited-suid' category of GTFOBins
.TP
\fBargparse-manpage linux\fR \fI\,all\/\fR
search all categories of GTFOBins
.SH OPTIONS 'argparse-manpage linux shell'
usage: argparse-manpage linux shell [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux cmd'
usage: argparse-manpage linux cmd [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux rev'
usage: argparse-manpage linux rev [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux nrev'
usage: argparse-manpage linux nrev [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux bind'
usage: argparse-manpage linux bind [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux nbind'
usage: argparse-manpage linux nbind [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux upload'
usage: argparse-manpage linux upload [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux download'
usage: argparse-manpage linux download [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux write'
usage: argparse-manpage linux write [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux read'
usage: argparse-manpage linux read [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux load'
usage: argparse-manpage linux load [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux suid'
usage: argparse-manpage linux suid [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux sudo'
usage: argparse-manpage linux sudo [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux cap'
usage: argparse-manpage linux cap [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux lsuid'
usage: argparse-manpage linux lsuid [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.SH OPTIONS 'argparse-manpage linux all'
usage: argparse-manpage linux all [-h] [-f] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-l\fR list, \fB\-\-list\fR list
list all types/categories/executables featured in the local copy of GTFOBins

.SH OPTIONS 'argparse-manpage windows'
usage: argparse-manpage windows [-h] [-l list]
                                {ads,awl,comp,copy,creds,decode,download,dump,encode,exec,recon,uac,upload,all}
                                ...

.SS
\fBSub-commands\fR
.TP
\fBargparse-manpage windows\fR \fI\,ads\/\fR
search the 'ADS' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,awl\/\fR
search the 'AWL Bypass' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,comp\/\fR
search the 'Compile' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,copy\/\fR
search the 'Copy' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,creds\/\fR
search the 'Credentials' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,decode\/\fR
search the 'Decode' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,download\/\fR
search the 'Download' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,dump\/\fR
search the 'Dump' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,encode\/\fR
search the 'Encode' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,exec\/\fR
search the 'Execute' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,recon\/\fR
search the 'Reconnaissance' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,uac\/\fR
search the 'UAC Bypass' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,upload\/\fR
search the 'Upload' category of LOLBAS
.TP
\fBargparse-manpage windows\fR \fI\,all\/\fR
search all categories of LOLBAS
.SH OPTIONS 'argparse-manpage windows ads'
usage: argparse-manpage windows ads [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows awl'
usage: argparse-manpage windows awl [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows comp'
usage: argparse-manpage windows comp [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows copy'
usage: argparse-manpage windows copy [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows creds'
usage: argparse-manpage windows creds [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows decode'
usage: argparse-manpage windows decode [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows download'
usage: argparse-manpage windows download [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows dump'
usage: argparse-manpage windows dump [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows encode'
usage: argparse-manpage windows encode [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows exec'
usage: argparse-manpage windows exec [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows recon'
usage: argparse-manpage windows recon [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows uac'
usage: argparse-manpage windows uac [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows upload'
usage: argparse-manpage windows upload [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.SH OPTIONS 'argparse-manpage windows all'
usage: argparse-manpage windows all [-h] [-f] [-t type] executable

.TP
\fBexecutable\fR
the executable to search for

.TP
\fB\-f\fR, \fB\-\-file\fR
use a file containing a list of executables (one per line) instead of a single
.br
executable

.TP
\fB\-t\fR type, \fB\-\-type\fR type
search for a specific type of executable

.TP
\fB\-l\fR list, \fB\-\-list\fR list
list all types/categories/executables featured in the local copy of LOLBAS

.SH AUTHORS
.B GTFOBLookup
was written by James Conlan <James.Conlan@nccgroup.com>.
.SH DISTRIBUTION
The latest version of GTFOBLookup may be downloaded from
.UR https://github.com/JamesConlan96/GTFOBLookup
.UE
